name: "Network Performance with iperf3 CI workflow"


on:
  push:
    branches: [ test ]
  schedule:
      # https://crontab.guru/examples.html #every friday at midnight  
      - cron:  '0 0 * * FRI' 
jobs:

  ubuntu-latest-iperf-job:
    name: "iperf docker clearlinux"
    runs-on: ubuntu-latest
    env:
      version: "latest"
      name: "clearlinux/iperf3"
      dockerdir: "dockerfiles"
      dockerfile: "Dockerfile.clearlinux.iperf3"               
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch    
    - name: "maximum bandwidth"
      run: |
          # destroyed afterwards (use --rm )
          # all subsequent Dockerfile commands generate new images and the cache is not used
          sudo docker build --no-cache --rm  -t ${name}:${version}  . --file ${dockerdir}/${dockerfile}                
          echo "###################################################################"
          echo "# ## # # Run as Server"
          echo "###################################################################"
          # Start server on the background
          docker run --rm --name=iperf3-srv -p 5201:5201 ${name}:${version} -s &
          docker image ls
          docker container ls
          docker network ls    
          SERVER_CONTAINER_IP=$(sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' iperf3-srv)
          echo $SERVER_CONTAINER_IP                
          # # https://gist.github.com/githubfoam/7f2edc5bd6bb5d30199360c7fccc04ae
          # ###################################################################
          # ## # # Run as Client (server IP address):
          # ###################################################################
          sudo docker run --rm --network=host ${name}:${version} -c $SERVER_CONTAINER_IP -u -b 1000m          
    - name: "UDP Tests"
      run: |
          # destroyed afterwards (use --rm )
          # all subsequent Dockerfile commands generate new images and the cache is not used
          sudo docker build --no-cache --rm  -t ${name}:${version}  . --file ${dockerdir}/${dockerfile}
          # ###################################################################
          # ## # # Run as Server
          # ################################################################### 
          # Start server on the background
          docker run --rm --name=iperf3-srv -p 5201:5201 ${name}:${version} -u -s &
          docker image ls
          docker container ls
          docker network ls
          docker port iperf3-srv # show all mapped ports of container
          SERVER_CONTAINER_IP=$(sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' iperf3-srv)
          echo $SERVER_CONTAINER_IP
          # ###################################################################
          # ## # # Run as Client (server IP address):
          # ###################################################################
          # https://gist.github.com/githubfoam/7f2edc5bd6bb5d30199360c7fccc04ae
          ###################################################################
          ## UDP Tests
          ###################################################################
          sudo docker run --rm --network=host ${name}:${version} -c $SERVER_CONTAINER_IP -u                 