name: "Network Performance with iperf3 CI workflow"


on:
  push:
    branches: [ test ]
  schedule:
      # https://crontab.guru/examples.html #every friday at midnight  
      - cron:  '0 0 * * FRI' 
jobs:

  ubuntu-latest-iperf-job:
    name: "iperf docker clearlinux"
    runs-on: ubuntu-latest
    env:
      version: "latest"
      name: "clearlinux/iperf"
      dockerdir: "dockerfiles"
      dockerfile: "Dockerfile.clearlinux.iperf3"               
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch    
    - name: "maximum bandwidth"
      run: |
          # destroyed afterwards (use --rm )
          # all subsequent Dockerfile commands generate new images and the cache is not used
          sudo docker build --no-cache --rm  -t ${name}:${version}  . --file ${dockerdir}/${dockerfile}            
          echo "###################################################################"
          echo "# ## # # Run as Server"
          echo "###################################################################"                  
          # Start server on the background
          # docker run --rm --name=iperf-srv -p 5201:5201 clearlinux/iperf -s &
          # Start server in daemon mode
          docker run --rm --name=iperf-srv -p 5201:5201 clearlinux/iperf -s -D
          docker image ls
          docker container ls
          docker network ls          
          # # https://gist.github.com/githubfoam/7f2edc5bd6bb5d30199360c7fccc04ae
          echo "###################################################################"
          echo "# ## # # Run as Client (server IP address):"
          echo "###################################################################"          
          # sudo docker run --rm --network=host clearlinux/iperf -c $CONTAINER_IP -u -b 1000m          
    - name: "UDP Tests"
      run: |
          # destroyed afterwards (use --rm )
          # all subsequent Dockerfile commands generate new images and the cache is not used
          sudo docker build --no-cache --rm  -t ${name}:${version}  . --file ${dockerdir}/${dockerfile}
          echo "###################################################################"
          echo "# ## # # Run as Server"
          echo "###################################################################" 
          # Start server in daemon mode
          docker run --rm --name=iperf-srv -p 5201:5201 clearlinux/iperf -u -s -D
          docker image ls
          docker container ls
          docker network ls
          docker port iperf-srv # show all mapped ports of container
          echo "###################################################################"
          echo "# ## # # Run as Client (server IP address):"
          echo "###################################################################" 
          # https://gist.github.com/githubfoam/7f2edc5bd6bb5d30199360c7fccc04ae
          echo "###################################################################"
          echo "## UDP Tests"
          echo "###################################################################"           
          # limits the bandwidth for UDP clients to 1 Mbit per second by default
          sudo docker run --rm --network=host clearlinux/iperf -u -c $CONTAINER_IP                  